version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - python
    commit-message:
      prefix: deps
    groups:
      python-dev-minor-patch:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github_actions
    commit-message:
      prefix: deps
    groups:
      codeql-action-minor-patch:
        patterns:
          - "github/codeql-action/*"
        update-types:
          - minor
          - patch
      github-actions-minor-patch:
        patterns:
          - "*"
        exclude-patterns:
          - "github/codeql-action/*"
        update-types:
          - minor
          - patch
